#!/usr/bin/env bash
# build.sh — Clone element-web v1.12.11, apply patches, build, and prepare output.
# Usage: ./client/build.sh
# The built output is placed in client/dist/

set -euo pipefail

ELEMENT_VERSION="v1.12.11"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="/tmp/cf-calls-matrix-element-build"
DIST_DIR="${SCRIPT_DIR}/dist"

echo "==> Building Element Web ${ELEMENT_VERSION} with cf-calls-matrix patches"

# Clean up any previous build attempt
rm -rf "${BUILD_DIR}"

echo "--> Cloning element-web ${ELEMENT_VERSION} (shallow)..."
git clone --depth 1 --branch "${ELEMENT_VERSION}" \
  https://github.com/element-hq/element-web.git "${BUILD_DIR}"

echo "--> Applying patches..."
cd "${BUILD_DIR}"
for patch in "${SCRIPT_DIR}"/patches/*.patch; do
  echo "    Applying: $(basename "${patch}")"
  git apply "${patch}"
done

echo "--> Installing dependencies (pnpm)..."
corepack enable pnpm 2>/dev/null || true
pnpm install --frozen-lockfile

echo "--> Building..."
pnpm build

echo "--> Preparing output in ${DIST_DIR}..."
rm -rf "${DIST_DIR}"
cp -r "${BUILD_DIR}/webapp" "${DIST_DIR}"

# Copy config.json if it exists (generated by setup.sh or CI)
if [ -f "${SCRIPT_DIR}/config.json" ]; then
  echo "--> Copying config.json into dist..."
  cp "${SCRIPT_DIR}/config.json" "${DIST_DIR}/config.json"
fi

# Copy .well-known if it exists
if [ -d "${SCRIPT_DIR}/.well-known" ]; then
  echo "--> Copying .well-known into dist..."
  cp -r "${SCRIPT_DIR}/.well-known" "${DIST_DIR}/.well-known"
fi

# Copy deployment files into dist so wrangler deploy can be run from there
cp "${SCRIPT_DIR}/worker.js"      "${DIST_DIR}/worker.js"
cp "${SCRIPT_DIR}/.assetsignore"  "${DIST_DIR}/.assetsignore"
if [ -f "${SCRIPT_DIR}/wrangler.toml" ]; then
  cp "${SCRIPT_DIR}/wrangler.toml" "${DIST_DIR}/wrangler.toml"
fi

echo "--> Cleaning up build directory..."
rm -rf "${BUILD_DIR}"

echo ""
echo "Build complete. Output in: ${DIST_DIR}"
echo "To deploy: cd ${DIST_DIR} && wrangler deploy"
